// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzwgrfawlgrnykltfglw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6d2dyZmF3bGdybnlrbHRmZ2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjUxNDIsImV4cCI6MjA2NjEwMTE0Mn0.fTLYGvTGkNb1OSzXVoQs_H0Wi4ngb0aQyFVI92Izpq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);